name: "Export secrets from GCP Secrets Manager" 

description: "Export secrets from GCP Secrets Manager to temporary secrets file" 

inputs:
  app-name:
    description: "The name of the application"
    required: true 
  environment:
    description: "The environment (e.g., dev, staging, prod)"
    required: true
  vault-env-keys:
    description: "The environment variable keys to be used for the vault secrets"
    required: true 
  secrets-file:
    description: "The path to the secrets file in the repository"
    required: true

runs:
  using: "composite"
  steps:

    - name: Make file executable
      run: chmod +x ${{ github.action_path }}/main.sh
      shell: bash

    - name: Run main script
      shell: bash
      run: | 
       ${{ github.action_path }}/main.sh ${{ inputs.app-name }} ${{ inputs.environment }} ${{ inputs.vault-env-keys }} ${{ inputs.secrets-file }}