repositories:
# Cloud Posse incubator repo of helm charts
- name: "cloudposse-incubator"
  url: "https://charts.cloudposse.com/incubator/"
- name: "bedag"
  url: "https://bedag.github.io/helm-charts/"

releases:
#
# References:
#   - https://github.com/cloudposse/charts/tree/master/incubator/monochart
#
- name: '{{ .Values.deployment.app_name }}'
  labels:
    preview: "true"
  chart: "cloudposse-incubator/monochart"
  version: "0.26.0"
  wait: true
  force: true
  recreatePods: false
  values:
    - fullnameOverride: '{{ .Values.deployment.app_name }}'
      nameOverride: '{{ .Values.deployment.app_name }}'
      serviceAccountName: '{{ .Values.deployment.app_name }}'
      image:
        repository: '{{ .Values.IMAGE_NAME }}'
        tag: '{{ .Values.IMAGE_TAG }}'
        pullPolicy: Always
      replicaCount: 2

      # Deployment configuration
      deployment:
        enabled: true
        annotations:
          reloader.stakater.com/auto: "true" # Reload pods for any modification of a ConfigMap or Secret
        strategy:
          type: "RollingUpdate"
          rollingUpdate:
            maxUnavailable: 1
        revisionHistoryLimit: 10

      # Configuration Settings
      configMaps:
        default:
          enabled: true

      # Service endpoint 
      service:
        enabled: true
        type: LoadBalancer
        ports:
          default:
            internal: 8080
            external: 80


      resources:
        requests:
          memory: 10Mi
          cpu: 100m
        limits:
          memory: 10Mi
        cpu: 100m
    - name: '{{ .Values.deployment.app_name }}-secrets' # Consistent with first release name
      chart: 'bedag/raw'
      version: '2.0.0'
      values:
        - resources:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: {{ .Values.deployment.app_name }} # Consistent secret name
            spec:
              refreshInterval: 60s
              secretStoreRef:
                name: gcp-secret-manager-store
                kind: SecretStore
              target:
                name: {{ .Values.deployment.app_name }} # Consistent secret target name
                creationPolicy: Owner
              data:
              {{ $service_secret_sm_path := .Values.deployment.service_secret_sm_path }}
              {{ range $i, $envar_key := .Values.deployment.envar_keys }}
                - secretKey: {{ $envar_key }}
                  remoteRef:
                    key: {{ $service_secret_sm_path }}-{{ $envar_key }}
              {{ end }}



  