# my-chart/values.yaml (this is what you provide to inputs.helm-values-file)

replicaCount: 1

deployment:
  app_name: "my-example-app" # <-- Changed from appName to app_name here

ingress:
  host: ""