
replicaCount: 1


deployment:
  appName: "example-app"


image:
  repository: "us-east4-docker.pkg.dev/cch-plat-glb-dev-project-4/cch-cicd-test/anilbelgod/example-app"
  tag: 'sha-b113bd3e011c8bcba64bd56f8ba5a6db713b7b14'


ingress:
 
  host: ""