image:
  repository: gcr.io/cch-plat-dev/example-app
  tag: latest

deployment:
  envar_keys:
    - db-user
    - gcp-region
  region: us-east4
  app_name: example-app
  service_secret_sm_path: service-example-app-secret-plat
  config_app_name: example-app
  branch_or_tag_name: ""
  namespace: cch-plat-dev
  version: 3781e9b7fd8022920a5379241dad8cf1c9372a6f
  repo_values:
    deploy:
      rolling_update:
        max_surge: 25%
        max_unavailable: 0
    auto_scaler:
      min_replicas: 1
      max_replicas: 3
    resources:
      requests:
        cpu: 200m
        memory: 800Mi
      limits:
        cpu: 250m
        memory: 1000Mi
  dynamic_values: {}


  