name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        shell: bash
        run: |
          terraform init -chdir=../bucket

      - name: Terraform Apply
        id: terraform-plan
        shell: bash
        run: |
          terraform apply -chdir=../bucket