name: "Deployment GitHub SHA"
description: "Get GitHub SHA for deployment."
outputs:
  value:
    description: "The GitHub SHA to use for deployments"
    value: ${{ steps.github-sha.outputs.value }}
runs:
  using: "composite"
  steps:
      - name: Determine the GitHub SHA to use
        id: github-sha
        uses: cloudposse/github-action-yaml-config-query@0.1.2
        with:
          query: .${{ github.event.pull_request.head.sha == '' }}
          config: |
            true:
              value: ${{ github.sha }}
            false:
              value: ${{ github.event.pull_request.head.sha }}

      - name: Echo SHAs
        shell: bash
        run: |
          echo 'github.sha: ${{ github.sha }}'
          echo 'github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}'
          echo 'selected sha: ${{ steps.github-sha.outputs.value }}'