name: Actions Runner Controller Demo
on:
  push:
    branches:
      - dev # Replace 'main' with the branch name you want to target

jobs:
  terraform-plan:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7 # or any version you prefer

      - name: Terraform Init
        id: init
        shell: bash
        run: |
          terraform init 
          echo $GOOGLE_APPLICATION_CREDENTIALS

      - name: Terraform Apply
        id: terraform-plan
        shell: bash
        run: |
          terraform apply -auto-approve








