name: apply Atmos Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [closed, reopened, synchronize]
    branches:
      - ft-atmos-pipeline

jobs:
  atmos-apply:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Atmos Environment
        uses: ./.github/actions/setup-atmos

      - name: Atmos Terraform init
        id: atmos-init
        run: |
          atmos terraform init google-storage-bucket --stack plat-gbl-dev

      - name: Atmos Terraform plan
        id: atmos-plan  
        run: |
          atmos terraform plan google-storage-bucket --stack plat-gbl-dev

  atmos-approve-and-apply:
    runs-on: ["self-hosted"]
    needs: atmos-apply
    environment:
      name: apply-approval   # <-- Create this environment in GitHub and add required reviewers
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Atmos Environment
        uses: ./.github/actions/setup-atmos

      - name: Atmos Terraform apply
        id: atmos-apply
        environment:
          name: apply-approval   # <-- Create this environment in GitHub and add required reviewers
        run: |
          atmos terraform apply google-storage-bucket --stack plat-gbl-dev
