name: Atmos Plan Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - ft-atmos-pipeline
  pull_request:
    branches:
      - ft-atmos-pipeline

jobs:
  atmos-plan:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Atmos Environment
        uses: ./.github/actions/setup-atmos

      - name: Atmos Terraform init
        id: atmos-init
        run: |
          atmos terraform init google-storage-bucket --stack plat-gbl-dev

      - name: Atmos Terraform plan
        id: atmos-plan
        run: |
          atmos terraform plan google-storage-bucket --stack plat-gbl-dev

      - name: Atmos Terraform plan output
        run: |
          atmos terraform plan google-storage-bucket --stack plat-gbl-dev --output-file plan_output.json
          cat plan_output.json
          echo "Plan output saved to plan_output.json"