name: |-
  CI - Build Docker image
  ```
on:
  workflow_call:
    inputs:
      organization:
        description: "Repository owner organization (ex. acme for repo acme/example)"
        required: true
        type: string
      environment:
        description: "The target environment for the build"
        required: true
        type: string
      repository:
        description: "Repository name (ex. example for repo acme/example)"
        required: true
        type: string
      tenant:
        description: "The tenant for the deployment"
        required: true
        type: string
      app-name:
        description: "Application name usually repository name"
        required: true
        type: string
      config-app-name:
        description: "The application name for configuration purposes"
        required: false
        type: string
      registry:
        description: "ECR Docker registry"
        required: true
        type: string
      run-tests:
        description: "Whether to run tests"
        required: false
        type: boolean
        default: true
      ar-region:
        description: "Artifact Registry region"
        required: true
        type: string
    # secrets:
    #   github-private-actions-pat:
    #     description: "Github PAT allow to pull private repos"
    #     required: true
    #   docker-build-push-secrets:
    #     description: "The secrets for authorizing access to private repos for a docker build"
    #     required: false      
    # outputs:
    #   image:
    #     description: "Docker Image"
    #     value: ${{ jobs.build-image.outputs.image }}
    #   image-tag:
    #     description: "Docker image tag"
    #     value: ${{ jobs.build-image.outputs.image-tag }}
    #   version:
    #     description: "The verion of the app"
    #     value: ${{ jobs.build-image.outputs.version }}

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ["arc-runner-set"]
    steps:
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
 
      # - name: Install Docker
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker.io
      #     sudo dockerd &  # Start Docker daemon in the background
      #     sleep 5         # Wait for the daemon to initialize
      #     docker --version

      # - name: Set up Docker
      #   uses: docker/setup-docker-action@v4  

      - name: Determine the application name for configuration purposes
        id: config-app-name
        uses: cloudposse/github-action-yaml-config-query@0.1.2
        with:
          query: .${{ inputs.config-app-name == '' }}
          config: |
            true:
              value: ${{ inputs.app-name }}
            false:
              value: ${{ inputs.config-app-name }}

      # - name: Environment Info
      #   uses: github-action-interface-environment@main
      #   id: environment
      #   with:
      #     implementation_repository: carecloud/actions-private #! Not able to access action-private repo.
      #     implementation_path: argocd-environments
      #     implementation_ref: main
      #     implementation_github_pat: ${{ secrets.github-private-actions-pat }}
      #     environment: ${{ inputs.environment }}
      #     namespace: ${{ inputs.environment }}
      #     repository: ${{ inputs.repository }}
      #     config-app-name: ${{ steps.config-app-name.outputs.value }}
      #     tenant: ${{ inputs.tenant }}

    # outputs:
    #   config-app-name: ${{ steps.config-app-name.outputs.value }}
    #   environment: ${{ inputs.environment }}
    #   # build-role: ${{ steps.environment.outputs.build-role }}


  build-image:
    runs-on: ["ubuntu-latest"]
    needs: [ "setup" ]
    steps:

      # - name: Determine the GitHub SHA to use
      #   uses: 66degrees/cch-app-cicd-test/.github/actions/github-sha.yml@main

      #   id: github-sha

      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ steps.github-sha.outputs.value }}
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

  #     - name: Login to Docker Hub  
  #       uses: docker/login-action@v3
  #       with:
  #         # registry: proget.medicomp.com
  #         username: ${{ secrets.docker-login }}
  #         password: ${{ secrets.docker-password }}   

      - name: Change string case of the organization
        id: change-string-case-organization
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ inputs.organization }}

      - name: Build
        id: build
        uses: jayz-66/github-action-docker-build-push@main
        with:
          organization: ${{ steps.change-string-case-organization.outputs.lowercase }}
          repository: ${{ needs.setup.outputs.config-app-name }}
          registry: ${{ inputs.registry }}
          secrets: ${{ secrets.docker-build-push-secrets }}
          docker-metadata-pr-head-sha: true

  #     # - uses: cloudposse/github-action-secret-outputs@0.1.2
  #     #   id: image
  #     #   with:
  #     #     secret: ${{ secrets.secret-outputs-passphrase }}
  #     #     op: encode
  #     #     in: ${{ steps.build.outputs.image }}

  #   outputs:
  #     image: ${{ steps.image.outputs.out }}
  #     image-tag: ${{ steps.build.outputs.tag }}
  #     version: ${{ steps.github-sha.outputs.value }}

  # test:
  #   runs-on: ["self-hosted"]
  #   needs: [ build-image ]
  #   if: ${{ inputs.run-tests == true }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: 'auth'
  #       uses: 'google-github-actions/auth@v2'
  #       with:
  #         workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
  #         service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

  #     - name: Tests
  #       id: test
  #       uses: jayz-66/github-action-docker-compose-test-run
  #       with:
  #         file: test/docker-compose.yaml
  #         service: app
  #         command: test/test.sh
  #         registry: ${{ inputs.registry }}






