# .github/workflows/build-with-kaniko.yml

name: Build with kaniko (Build Only with Checkout)

on:
  push:
    branches: [ "test-ci/cd" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  build-to-ghcr:
    name: Build for GHCR (no push, with checkout)
    runs-on: ["gha-runner-scale-set"]
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug # the kaniko image
    permissions:
      contents: read # read the repository for actions/checkout