name: 2 - Dev Branch
on:
  push:
    branches: [ dev ]

permissions:
  contents: write
  id-token: write

jobs:
  do:
    uses: ./.github/workflows/setup.yaml 
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      app-name: "${{ vars.APP_NAME }}"
      tenant: "${{ vars.TENANT }}"
      ar-region: "${{ vars.AR_REGION }}" 
      registry: "${{ vars.AR_REGISTRY }}" 
      helm-values-file: "./deploy/values/dev.yaml"   
      # deployment-check-retry-count: "30"  
      # deployment-check-app-id: ${{ vars.CCH_DEPLOYMENT_STATUS_APP_ID }}   
      # deployment-check-app-installation-id: ${{ vars.CCH_DEPLOYMENT_STATUS_APP_INSTALLATION_ID }} 
      run-tests: true #CI 
    secrets:
      one-password-service-account-token: "${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT_TOKEN }}"
      github-private-actions-pat: "${{ secrets.GIT_PAT }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
    #   deployment-check-app-private-key: ${{ secrets.CCH_DEPLOYMENT_STATUS_APP_PRIVATE_KEY }}
  
    