# .github/workflows/build-with-kaniko.yml

name: Build with kaniko (Build Only with Checkout)

on:
  push:
    branches: [ "test-ci/cd" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

jobs:
  build-to-ghcr:
    name: Build for GHCR (no push, with checkout)
    runs-on: ["gha-runner-scale-set"]
# uses self-hosted runner scale set
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug # the kaniko image
    permissions:
      contents: read # read the repository for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image with kaniko (no push)
        run: |
          # Authentication block removed
          /kaniko/executor --dockerfile="./app/Dockerfile" \
            --context="${{ github.workspace }}"  \
            --destination="$GH_REGISTRY/$IMAGE_NAME:$(echo ${GITHUB_SHA} | head  -c 7)" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --no-push # Added to prevent pushing
            # --push-retry 5 # Removed: Not pushing
        env:
          # GIT_USERNAME: ${{ github.actor }} # Removed: Not needed when using actions/checkout
          # GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }} # Removed: Not needed when using actions/checkout
          GH_REGISTRY: "ghcr.io" # Kept for destination tagging consistency
          IMAGE_NAME: "${{ github.repository }}/nginx" # Kept for destination tagging consistency

  build-to-acr:
    name: Build for ACR (no push, with checkout)
    runs-on: ["gha-runner-scale-set"]
# uses self-hosted runner scale set
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug # the kaniko image
    permissions:
      contents: read # read the repository for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image with kaniko (no push)
        run: |
          # Authentication block removed
          /kaniko/executor --dockerfile="./app/Dockerfile" \
            --context="${{ github.workspace }}"  \
            --destination="$ACR_URL/<namespace>/nginx:$(echo ${GITHUB_SHA} | head  -c 7)" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --no-push # Added to prevent pushing
            # --push-retry 5 # Removed: Not pushing
        env:
          # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} # Removed: Not pushing to ACR
          # AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} # Removed
          # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} # Removed
          # GIT_USERNAME: ${{ github.actor }} # Removed: Not needed when using actions/checkout
          # GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }} # Removed: Not needed when using actions/checkout
          ACR_URL: "myacr.azurecr.io" # Kept for destination tagging consistency

  build-to-docker-hub:
    name: Build for Docker Hub (no push, with checkout)
    runs-on: ["gha-runner-scale-set"]
# uses self-hosted runner scale set
    container:
      image: gcr.io/kaniko-project/executor:v1.20.0-debug 
    permissions:
      contents: read # read the repository for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image with kaniko (no push)
        run: |
          # Authentication block removed
          /kaniko/executor --dockerfile="./app/Dockerfile" \
            --context="${{ github.workspace }}"  \
            --destination="$DOCKER_IMAGE_NAME:$(echo ${GITHUB_SHA} | head  -c 7)" \
            ${{ env.KANIKO_CACHE_ARGS }} \
            --no-push # Added to prevent pushing
            # --push-retry 5 # Removed: Not pushing
        env: 
          # GIT_USERNAME: ${{ github.actor }} # Removed: Not needed when using actions/checkout
          # GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }} # Removed: Not needed when using actions/checkout
          DOCKER_IMAGE_NAME: "<docker-username>/nginx" # Kept for destination tagging consistency
                                                      # Replace <docker-username> if needed for clarity, though it won't be used for auth
