name: 2 - Dev Branch
on:
  push:
    branches: [ dev ]

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup yq
        uses: dcarbone/install-yq-action@v1.1.0
        with:
          version: v4.28.1
          download-compressed: true
          force: true

      - name: Setup helmfile
        uses: helmfile/helmfile-action@v2.0.2
        with:
          helmfile-version: v0.157.0 # https://github.com/helmfile/helmfile/releases
          helm-version: v3.13.0
      - name: Define Helm values file path
        if: ${{ inputs.toolchain == 'helmfile' }}
        id: deploy-helm-values-file-path
        shell: bash
        run: |
          echo '::set-output name=deploy::${{ runner.temp }}/resources.yaml'

      - name: Setup yq
        if: ${{ inputs.toolchain == 'helmfile' }}
        uses: dcarbone/install-yq-action@v1.1.0
        with:
            version: v4.35.1
            download-compressed: true
            force: true

      - name: Create deploy Helm values file
        if: ${{ inputs.toolchain == 'helmfile' }}
        uses: DamianReeves/write-file-action@master
        with:
            path: ${{ steps.deploy-helm-values-file-path.outputs.deploy }}
            contents: "# Empty file"

      - name: Check Current Working Directory
        shell: bash
        run: |
          pwd
          ls -la

      - name: Helmfile render
        if: ${{ inputs.toolchain == 'helmfile' && inputs.operation == 'deploy' }}
        shell: bash
        run: |
          helmfile --namespace gh-namespace \
            --environment dev \
            --file "actions/deploy-argocd/app.yaml" \
            --state-values-file "actions/deploy-argocd/dev.yaml" \
            template \
            > ${{ steps.deploy-helm-values-file-path.outputs.deploy }}
      # env:
      #   IMAGE_NAME: "us-east4-docker.pkg.dev/cch-plat-glb-dev-project-4/cch-cicd-test/anilbelgod/example-app"
      #   IMAGE_TAG: "latest"

      - name: Display Deploy Helm Values File
        shell: bash
        if: ${{ inputs.toolchain == 'helmfile' }}
        run: |
            cat ${{ runner.tmp }}/resources.yaml
            
